apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: pdb-poc
spec:
  destination:
    name: ''
    namespace: pdb-poc
    server: 'https://kubernetes.default.svc'
  source:
    path: pdb-poc/resources
    repoURL: 'https://github.com/osowski/gitops-demos.git'
    targetRevision: HEAD
  sources: []
  project: default
  syncPolicy:
    syncOptions: []
