apiVersion: v1
data:
  index.html: |
    <html>
    <head>
    <meta http-equiv="Refresh" content="5">
    <style>
      body {
        background-color: red;
        color: white;
      }
    </style>
    </head>
    <body>
    <!-- TODO: Add default css and auto page refresh logic -->
    <p>RED</p>
    </body>
    </html>
kind: ConfigMap
metadata:
  name: nginx-index-red
