apiVersion: v1
data:
  index.html: |
    <html>
    <body>
    <!-- TODO: Add default css and auto page refresh logic -->
    <p>RED</p>
    </body>
    </html>
kind: ConfigMap
metadata:
  name: nginx-index-red
