---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: deploy-04
  name: deploy-04
spec:
  replicas: 1
  selector:
    matchLabels:
      app: deploy-04
      scenario: pdb-poc
  strategy: {}
  template:
    metadata:
      labels:
        app: deploy-04
        scenario: pdb-poc
        current-rev: green
    spec:
      containers:
      - image: nginxinc/nginx-unprivileged
        name: nginx
        resources: {}
        volumeMounts:
        - mountPath: /usr/share/nginx/html
          name: nginx-index
      volumes:
      - name: nginx-index
        configMap:
          name: nginx-index
status: {}
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: deploy-04
  name: deploy-04
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 8080
  selector:
    app: deploy-04
    scenario: pdb-poc
  type: NodePort
status:
  loadBalancer: {}
---
