---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: deploy-03
  name: deploy-03
spec:
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 0
      maxUnavailable: 1
  replicas: 1
  selector:
    matchLabels:
      app: deploy-03
      scenario: pdb-poc
  template:
    metadata:
      labels:
        app: deploy-03
        scenario: pdb-poc
        current-rev: red
    spec:
      containers:
      - image: nginxinc/nginx-unprivileged
        name: nginx
        resources: {}
        volumeMounts:
        - mountPath: /usr/share/nginx/html
          name: nginx-index
      volumes:
      - name: nginx-index
        configMap:
          name: nginx-index
status: {}
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: deploy-03
  name: deploy-03
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 8080
  selector:
    app: deploy-03
    scenario: pdb-poc
  type: NodePort
status:
  loadBalancer: {}
---
